version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ .BuildNum }}-{{ checksum "package.json" }}
            - dependency-cache-{{ .Branch }}-{{ .BuildNum }}
            - dependency-cache
      - run: yarn
      - run: yarn test
      - run: yarn test:coverage
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: coverage.lcov
workflows:
  version: 2
  build_test:
    jobs:
      - build
